# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sexe',
            field=models.BooleanField(default=True),
        ),
    ]
