# Generated by Django 2.0.1 on 2018-01-04 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
