# Generated by Django 2.0 on 2017-12-21 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conseil',
            name='ligneordonnance_ptr',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='ligneordonnance_ptr',
        ),
        migrations.DeleteModel(
            name='Conseil',
        ),
        migrations.DeleteModel(
            name='Medicament',
        ),
    ]
