# Generated by Django 2.0 on 2017-12-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnances', '0002_auto_20171221_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conseil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cip', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=200)),
                ('posologie', models.CharField(max_length=200)),
                ('duree', models.PositiveIntegerField()),
            ],
        ),
    ]
