# Generated by Django 2.0.1 on 2018-01-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnances', '0002_auto_20180104_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conseil',
            name='position',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='position',
        ),
    ]
