# Generated by Django 2.0 on 2017-12-31 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnances', '0004_auto_20171221_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneordonnance',
            name='ordonnance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ordonnances.Ordonnance'),
        ),
    ]
