# Generated by Django 2.0 on 2017-12-31 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnances', '0005_auto_20171231_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conseil',
            old_name='contenu',
            new_name='texte',
        ),
    ]
