language: python

sudo: false

python:
  - "3.5"
  - "3.6"
env:
  - DJANGO="1.11"
#  - DJANGO="2.0"

# command to install dependencies

# command to run tests
#
install:
  - pip install -U tox-travis

script:
    - tox
