language: python

python:
<<<<<<< HEAD
    - "3.5"
    - "3.6"
=======
  - "3.5"
  - "3.6"
env:
  - DJANGO="1.11"
  - DJANGO="2.0"
>>>>>>> refactorproject

# command to install dependencies

# command to run tests
#
install:
  - pip install -U tox-travis

script:
    - tox
