# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
