# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 11:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unologbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL), ),
        migrations.AddField(
            model_name='observation',
            name='patient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='unologbase.Patient'), ),
    ]
