# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unologbase', '0002_auto_20170809_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
