# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unologbase', '0005_auto_20170811_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administratif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='administratif',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='unologbase.Administratif'),
            preserve_default=False,
        ),
    ]
