# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unologbase', '0006_auto_20170812_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='administratif',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='unologbase.Administratif'),
        ),
    ]
