# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unologbase', '0007_auto_20170812_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='administratif',
        ),
        migrations.DeleteModel(
            name='Administratif',
        ),
    ]
