# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unologbase', '0008_auto_20170814_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='street',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
