# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actes', '0003_auto_20171124_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='patients.Patient'),
        ),
    ]
