# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0003_patient_alive'),
        ('medics', '0001_initial'),
        ('actes', '0004_auto_20171124_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('medic', models.ManyToManyField(related_name='medics', to='medics.Medic')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordonnances', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='patients.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
