# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unousers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unouser',
            name='statut',
            field=models.CharField(default='medecin', max_length=20),
            preserve_default=False,
        ),
    ]
