# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unousers', '0002_unouser_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unouser',
            name='statut',
            field=models.CharField(choices=[('medecin', 'Médecin'), ('secretaire', 'Secrétaire'), ('interne', 'Interne'), ('remplacant', 'Remplaçant')], max_length=20),
        ),
    ]
