# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sexe',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
