# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cip', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=200)),
                ('posologie', models.CharField(max_length=200)),
                ('duree', models.PositiveIntegerField()),
                ('ald', models.BooleanField(default=False)),
            ],
        ),
    ]
